const CACHE_NAME = 'ceforaa-tablet-part4-offline-v1';
const PRECACHE_URLS = [
  "./Huanipaca.geojson",
  "./Huanipaca_degradation.png",
  "./Huanipaca_dem_relief.jpg",
  "./Huanipaca_firerisk.png",
  "./Huanipaca_labels.geojson",
  "./Huanipaca_landuse.png",
  "./Huanipaca_satellite.jpg",
  "./Huanipaca_water.png",
  "./Huanipca_landuse.png",
  "./SFO_degradation.png",
  "./SJO.geojson",
  "./SJO_degradation.png",
  "./SJO_dem_relief.jpg",
  "./SJO_firerisk.png",
  "./SJO_labels.geojson",
  "./SJO_landuse.png",
  "./SJO_satellite.jpg",
  "./SJO_water.png",
  "./Yanatile.geojson",
  "./Yanatile_degradation.png",
  "./Yanatile_dem_relief.jpg",
  "./Yanatile_firerisk.png",
  "./Yanatile_labels.geojson",
  "./Yanatile_landuse.png",
  "./Yanatile_satellite.jpg",
  "./Yanatile_water.png",
  "./data/basin_Huanipaca_10km2.geojson",
  "./data/basin_Huanipaca_2km2.geojson",
  "./data/basin_SJO_10km2.geojson",
  "./data/basin_SJO_2km2.geojson",
  "./data/basin_Yanatile_10km2.geojson",
  "./data/basin_Yanatile_2km2.geojson",
  "./data/simulation/Huanipaca/10km2/10.geojson",
  "./data/simulation/Huanipaca/10km2/104.geojson",
  "./data/simulation/Huanipaca/10km2/106.geojson",
  "./data/simulation/Huanipaca/10km2/110.geojson",
  "./data/simulation/Huanipaca/10km2/116.geojson",
  "./data/simulation/Huanipaca/10km2/118.geojson",
  "./data/simulation/Huanipaca/10km2/120.geojson",
  "./data/simulation/Huanipaca/10km2/14.geojson",
  "./data/simulation/Huanipaca/10km2/18.geojson",
  "./data/simulation/Huanipaca/10km2/20.geojson",
  "./data/simulation/Huanipaca/10km2/22.geojson",
  "./data/simulation/Huanipaca/10km2/26.geojson",
  "./data/simulation/Huanipaca/10km2/28.geojson",
  "./data/simulation/Huanipaca/10km2/32.geojson",
  "./data/simulation/Huanipaca/10km2/34.geojson",
  "./data/simulation/Huanipaca/10km2/4.geojson",
  "./data/simulation/Huanipaca/10km2/42.geojson",
  "./data/simulation/Huanipaca/10km2/46.geojson",
  "./data/simulation/Huanipaca/10km2/50.geojson",
  "./data/simulation/Huanipaca/10km2/60.geojson",
  "./data/simulation/Huanipaca/10km2/62.geojson",
  "./data/simulation/Huanipaca/10km2/64.geojson",
  "./data/simulation/Huanipaca/10km2/66.geojson",
  "./data/simulation/Huanipaca/10km2/68.geojson",
  "./data/simulation/Huanipaca/10km2/70.geojson",
  "./data/simulation/Huanipaca/10km2/72.geojson",
  "./data/simulation/Huanipaca/10km2/74.geojson",
  "./data/simulation/Huanipaca/10km2/76.geojson",
  "./data/simulation/Huanipaca/10km2/78.geojson",
  "./data/simulation/Huanipaca/10km2/8.geojson",
  "./data/simulation/Huanipaca/10km2/82.geojson",
  "./data/simulation/Huanipaca/10km2/84.geojson",
  "./data/simulation/Huanipaca/10km2/86.geojson",
  "./data/simulation/Huanipaca/10km2/88.geojson",
  "./data/simulation/Huanipaca/10km2/90.geojson",
  "./data/simulation/Huanipaca/10km2/92.geojson",
  "./data/simulation/Huanipaca/10km2/94.geojson",
  "./data/simulation/Huanipaca/10km2/96.geojson",
  "./data/simulation/Huanipaca/10km2/98.geojson",
  "./data/simulation/Huanipaca/2km2/100.geojson",
  "./data/simulation/Huanipaca/2km2/112.geojson",
  "./data/simulation/Huanipaca/2km2/114.geojson",
  "./data/simulation/Huanipaca/2km2/116.geojson",
  "./data/simulation/Huanipaca/2km2/120.geojson",
  "./data/simulation/Huanipaca/2km2/124.geojson",
  "./data/simulation/Huanipaca/2km2/160.geojson",
  "./data/simulation/Huanipaca/2km2/164.geojson",
  "./data/simulation/Huanipaca/2km2/166.geojson",
  "./data/simulation/Huanipaca/2km2/168.geojson",
  "./data/simulation/Huanipaca/2km2/170.geojson",
  "./data/simulation/Huanipaca/2km2/172.geojson",
  "./data/simulation/Huanipaca/2km2/174.geojson",
  "./data/simulation/Huanipaca/2km2/176.geojson",
  "./data/simulation/Huanipaca/2km2/178.geojson",
  "./data/simulation/Huanipaca/2km2/180.geojson",
  "./data/simulation/Huanipaca/2km2/182.geojson",
  "./data/simulation/Huanipaca/2km2/184.geojson",
  "./data/simulation/Huanipaca/2km2/186.geojson",
  "./data/simulation/Huanipaca/2km2/188.geojson",
  "./data/simulation/Huanipaca/2km2/190.geojson",
  "./data/simulation/Huanipaca/2km2/192.geojson",
  "./data/simulation/Huanipaca/2km2/194.geojson",
  "./data/simulation/Huanipaca/2km2/196.geojson",
  "./data/simulation/Huanipaca/2km2/198.geojson",
  "./data/simulation/Huanipaca/2km2/20.geojson",
  "./data/simulation/Huanipaca/2km2/200.geojson",
  "./data/simulation/Huanipaca/2km2/202.geojson",
  "./data/simulation/Huanipaca/2km2/204.geojson",
  "./data/simulation/Huanipaca/2km2/206.geojson",
  "./data/simulation/Huanipaca/2km2/208.geojson",
  "./data/simulation/Huanipaca/2km2/210.geojson",
  "./data/simulation/Huanipaca/2km2/212.geojson",
  "./data/simulation/Huanipaca/2km2/214.geojson",
  "./data/simulation/Huanipaca/2km2/216.geojson",
  "./data/simulation/Huanipaca/2km2/218.geojson",
  "./data/simulation/Huanipaca/2km2/220.geojson",
  "./data/simulation/Huanipaca/2km2/222.geojson",
  "./data/simulation/Huanipaca/2km2/224.geojson",
  "./data/simulation/Huanipaca/2km2/226.geojson",
  "./data/simulation/Huanipaca/2km2/228.geojson",
  "./data/simulation/Huanipaca/2km2/230.geojson",
  "./data/simulation/Huanipaca/2km2/232.geojson",
  "./data/simulation/Huanipaca/2km2/234.geojson",
  "./data/simulation/Huanipaca/2km2/236.geojson",
  "./data/simulation/Huanipaca/2km2/238.geojson",
  "./data/simulation/Huanipaca/2km2/24.geojson",
  "./data/simulation/Huanipaca/2km2/240.geojson",
  "./data/simulation/Huanipaca/2km2/242.geojson",
  "./data/simulation/Huanipaca/2km2/250.geojson",
  "./data/simulation/Huanipaca/2km2/252.geojson",
  "./data/simulation/Huanipaca/2km2/254.geojson",
  "./data/simulation/Huanipaca/2km2/256.geojson",
  "./data/simulation/Huanipaca/2km2/258.geojson",
  "./data/simulation/Huanipaca/2km2/260.geojson",
  "./data/simulation/Huanipaca/2km2/262.geojson",
  "./data/simulation/Huanipaca/2km2/266.geojson",
  "./data/simulation/Huanipaca/2km2/268.geojson",
  "./data/simulation/Huanipaca/2km2/270.geojson",
  "./data/simulation/Huanipaca/2km2/272.geojson",
  "./data/simulation/Huanipaca/2km2/274.geojson",
  "./data/simulation/Huanipaca/2km2/276.geojson",
  "./data/simulation/Huanipaca/2km2/278.geojson",
  "./data/simulation/Huanipaca/2km2/28.geojson",
  "./data/simulation/Huanipaca/2km2/280.geojson",
  "./data/simulation/Huanipaca/2km2/282.geojson",
  "./data/simulation/Huanipaca/2km2/284.geojson",
  "./data/simulation/Huanipaca/2km2/286.geojson",
  "./data/simulation/Huanipaca/2km2/288.geojson",
  "./data/simulation/Huanipaca/2km2/290.geojson",
  "./data/simulation/Huanipaca/2km2/292.geojson",
  "./data/simulation/Huanipaca/2km2/294.geojson",
  "./data/simulation/Huanipaca/2km2/296.geojson",
  "./data/simulation/Huanipaca/2km2/298.geojson",
  "./data/simulation/Huanipaca/2km2/308.geojson",
  "./data/simulation/Huanipaca/2km2/310.geojson",
  "./data/simulation/Huanipaca/2km2/312.geojson",
  "./data/simulation/Huanipaca/2km2/314.geojson",
  "./data/simulation/Huanipaca/2km2/316.geojson",
  "./data/simulation/Huanipaca/2km2/318.geojson",
  "./data/simulation/Huanipaca/2km2/320.geojson",
  "./data/simulation/Huanipaca/2km2/324.geojson",
  "./data/simulation/Huanipaca/2km2/36.geojson",
  "./data/simulation/Huanipaca/2km2/362.geojson",
  "./data/simulation/Huanipaca/2km2/368.geojson",
  "./data/simulation/Huanipaca/2km2/370.geojson",
  "./data/simulation/Huanipaca/2km2/372.geojson",
  "./data/simulation/Huanipaca/2km2/378.geojson",
  "./data/simulation/Huanipaca/2km2/40.geojson",
  "./data/simulation/Huanipaca/2km2/42.geojson",
  "./data/simulation/Huanipaca/2km2/436.geojson",
  "./data/simulation/Huanipaca/2km2/438.geojson",
  "./data/simulation/Huanipaca/2km2/44.geojson",
  "./data/simulation/Huanipaca/2km2/448.geojson",
  "./data/simulation/Huanipaca/2km2/46.geojson",
  "./data/simulation/Huanipaca/2km2/470.geojson",
  "./data/simulation/Huanipaca/2km2/472.geojson",
  "./data/simulation/Huanipaca/2km2/474.geojson",
  "./data/simulation/Huanipaca/2km2/476.geojson",
  "./data/simulation/Huanipaca/2km2/478.geojson",
  "./data/simulation/Huanipaca/2km2/48.geojson",
  "./data/simulation/Huanipaca/2km2/480.geojson",
  "./data/simulation/Huanipaca/2km2/482.geojson",
  "./data/simulation/Huanipaca/2km2/50.geojson",
  "./data/simulation/Huanipaca/2km2/58.geojson",
  "./data/simulation/Huanipaca/2km2/62.geojson",
  "./data/simulation/Huanipaca/2km2/66.geojson",
  "./data/simulation/Huanipaca/2km2/68.geojson",
  "./data/simulation/Huanipaca/2km2/70.geojson",
  "./data/simulation/Huanipaca/2km2/74.geojson",
  "./data/simulation/Huanipaca/2km2/78.geojson",
  "./data/simulation/Huanipaca/2km2/80.geojson",
  "./data/simulation/Huanipaca/2km2/88.geojson",
  "./data/simulation/Huanipaca/2km2/90.geojson",
  "./data/simulation/Huanipaca/2km2/94.geojson",
  "./data/simulation/Huanipaca/2km2/96.geojson",
  "./data/simulation/fire_risk_embedded.js",
  "./data/simulation/landuse_lookup.json",
  "./data/simulation/rasters/Huanipaca/current.bin",
  "./data/simulation/rasters/Huanipaca/fire_risk.bin",
  "./data/simulation/rasters/Huanipaca/flow_accumulation.bin",
  "./data/simulation/rasters/Huanipaca/flow_direction.bin",
  "./data/simulation/rasters/Huanipaca/meta.json",
  "./data/simulation/rasters/Huanipaca/nf.bin",
  "./data/simulation/rasters/Huanipaca/ot.bin",
  "./data/simulation/rasters/Huanipaca/pl.bin",
  "./data/simulation/rasters/Huanipaca/sf.bin",
  "./data/simulation/rasters/SJO/current.bin",
  "./data/simulation/rasters/SJO/fire_risk.bin",
  "./data/simulation/rasters/SJO/flow_accumulation.bin",
  "./data/simulation/rasters/SJO/flow_direction.bin",
  "./data/simulation/rasters/SJO/meta.json",
  "./data/simulation/rasters/SJO/nf.bin",
  "./data/simulation/rasters/SJO/ot.bin",
  "./data/simulation/rasters/SJO/pl.bin",
  "./data/simulation/rasters/SJO/sf.bin",
  "./data/simulation/rasters/Yanatile/current.bin",
  "./data/simulation/rasters/Yanatile/fire_risk.bin",
  "./data/simulation/rasters/Yanatile/flow_accumulation.bin",
  "./data/simulation/rasters/Yanatile/flow_direction.bin",
  "./data/simulation/rasters/Yanatile/meta.json",
  "./data/simulation/rasters/Yanatile/nf.bin",
  "./data/simulation/rasters/Yanatile/ot.bin",
  "./data/simulation/rasters/Yanatile/pl.bin",
  "./data/simulation/rasters/Yanatile/sf.bin",
  "./data/simulation/watershed_utm/Huanipaca_10km2.json",
  "./data/simulation/watershed_utm/Huanipaca_2km2.json",
  "./data/simulation/watershed_utm/SJO_10km2.json",
  "./data/simulation/watershed_utm/SJO_2km2.json",
  "./data/simulation/watershed_utm/Yanatile_10km2.json",
  "./data/simulation/watershed_utm/Yanatile_2km2.json",
  "./fires/Huanipaca_fire_2017.geojson",
  "./fires/Huanipaca_fire_2018.geojson",
  "./fires/Huanipaca_fire_2019.geojson",
  "./fires/Huanipaca_fire_2020.geojson",
  "./fires/Huanipaca_fire_2021.geojson",
  "./fires/Huanipaca_fire_2022.geojson",
  "./fires/Huanipaca_fire_2023.geojson",
  "./fires/Huanipaca_fire_2024.geojson",
  "./fires/Huanipaca_fire_2025.geojson",
  "./fires/SJO_fire_2017.geojson",
  "./fires/SJO_fire_2018.geojson",
  "./fires/SJO_fire_2019.geojson",
  "./fires/SJO_fire_2020.geojson",
  "./fires/SJO_fire_2021.geojson",
  "./fires/SJO_fire_2022.geojson",
  "./fires/SJO_fire_2023.geojson",
  "./fires/SJO_fire_2024.geojson",
  "./fires/SJO_fire_2025.geojson",
  "./fires/Yanatile_fire_2017.geojson",
  "./fires/Yanatile_fire_2018.geojson",
  "./fires/Yanatile_fire_2019.geojson",
  "./fires/Yanatile_fire_2020.geojson",
  "./fires/Yanatile_fire_2021.geojson",
  "./fires/Yanatile_fire_2022.geojson",
  "./fires/Yanatile_fire_2023.geojson",
  "./fires/Yanatile_fire_2024.geojson",
  "./fires/Yanatile_fire_2025.geojson",
  "./fires/service-worker.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./index.html",
  "./leaflet.css",
  "./leaflet.js",
  "./logo.png",
  "./manifest.json",
  "./manifest.webmanifest",
  "./visualization_dialog.py"
];


self.addEventListener('install', event => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then(async cache => {
      for (const url of PRECACHE_URLS) {
        try {
          await cache.add(new Request(url, {cache:'reload'}));
        } catch (e) {
          console.warn('Precache failed:', url, e);
        }
      }
    })
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.map(key => key===CACHE_NAME ? null : caches.delete(key)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  if(event.request.method !== 'GET') return;
  const req = event.request;

  event.respondWith(
    caches.match(req, {ignoreSearch:true}).then(cached => {
      if(cached) return cached;
      return fetch(req).then(resp => {
        if(resp && resp.ok){
          const copy = resp.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(req, copy));
        }
        return resp;
      }).catch(() => {
        if(req.mode === 'navigate'){
          return caches.match('./index.html', {ignoreSearch:true});
        }
        return new Response('', {status:504, statusText:'Offline'});
      });
    })
  );
});
